function(robotics_add_header_library target)
    cmake_parse_arguments(ARG "STATIC" "" "" ${ARGN})

    if (EMIL_ENABLE_COVERAGE)
        if (ARG_STATIC)
            add_library(${target} ${EMIL_EXCLUDE_FROM_ALL} STATIC)
        else()
            add_library(${target} ${EMIL_EXCLUDE_FROM_ALL})
        endif()
        set(ROBOTICS_VISIBILITY PUBLIC PARENT_SCOPE)
    else()
        add_library(${target} ${EMIL_EXCLUDE_FROM_ALL} INTERFACE)
        set(ROBOTICS_VISIBILITY INTERFACE PARENT_SCOPE)
    endif()
endfunction()

function(robotics_add_coverage_sources target)
    if (EMIL_ENABLE_COVERAGE)
        target_sources(${target} PRIVATE ${ARGN})
    endif()
endfunction()
